version: "3"

services:

  app:
    build: .
    restart: always
    environment:
      - NODEJS_PORT=8080
      - NODEJS_IP=0.0.0.0
      - GITHUB_TOKEN=<INSERT_YOUR_GITHUB_TOKEN>
    ports:
      - 8080:8080