version: "3"

networks:
  proxy:
  db:

services:

  app:
    build: .
    restart: always
    environment:
      - NODEJS_PORT=3000
      - NODEJS_IP=0.0.0.0
      - GITHUB_TOKEN=<INSERT_YOUR_GITHUB_TOKEN>
      - MONGODB_DB_URL=mongodb://mongo/lighthouse
    labels:
      - traefik.enable=true
      - traefik.backend=lighthouse_app
      - traefik.frontend.rule=Host:www.github-lighthouse.me,github-lighthouse.me
      - traefik.docker.network=lighthouse_proxy
      - traefik.port=3000
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - db
      - proxy
    depends_on:
      - mongo
  
  mongo:
    restart: always
    image: mongo
    volumes:
      - /data/db:/data/db
    labels:
      - traefik.enable=false
      - traefik.docker.network=lighthouse_db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - db

  traefik:
    restart: always
    image: traefik:1.3.8-alpine
    command: --configFile=/var/traefik/traefik.toml
    volumes:
      - /traefik/acme.json:/etc/acme.json
      - /traefik/traefik.toml:/var/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy