version: "3"

services:

  app:
    build: .
    restart: always
    environment:
      - NODEJS_PORT=3000
      - NODEJS_IP=0.0.0.0
      - GITHUB_TOKEN=<YOU_GITHUB_TOKEN>
      - MONGODB_DB_URL=mongodb://mongo/lighthouse
    ports:
      - 80:3000
    depends_on:
      - mongo
  
  mongo:
    restart: always
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - 127.0.0.1:27017:27017