defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "mathias.gilson@outlook.com"
storage = "/etc/acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
dnsProvider = "cloudflare"

# Enable Docker configuration backend
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
endpoint = "unix:///var/run/docker.sock"

# Enable watch docker changes
watch = true


[accessLog]
filePath = "/tmp/logs.log"
format = "json"